#!/bin/bash

_1=(1 09 25 10 55)
_2=(2 11 10 12 40)
_3=(3 13 00 14 30)
_4=(4 14 45 16 15)
_5=(5 16 30 18 00)
_6=(6 18 10 19 40)
_7=(7 19 50 21 20)


schedule=(${_1[@]} ${_2[@]} ${_3[@]} ${_4[@]} ${_5[@]} ${_6[@]} ${_7[@]})
H=`date +%H`
M=`date +%M`
H=`expr $H + 0`
M=`expr $M + 0`
echo "現在時刻: $H:$M"

declare -i i=0
li=(0 1 2 3 4 5 6)
for m in ${li[@]}; do
  n0=`expr ${i} + 0`
  n1=`expr ${i} + 1`
  n2=`expr ${i} + 2`
  n3=`expr ${i} + 3`
  n4=`expr ${i} + 4`
  H_1=`expr $H - ${schedule[$n1]}`
  H_2=`expr ${schedule[${n3}]} - $H`
  H_3=`expr ${schedule[${n3}]} - ${schedule[${n1}]}`
  M_1=`expr $M - ${schedule[${n2}]}`
  M_2=`expr ${schedule[${n4}]} - $M`
  time=90
  #echo "${H_1} ${H_2} ${H_3} ${M_1} ${M_2}"
  echo "${schedule[${n0}]}限 ${schedule[${n1}]}:${schedule[${n2}]} ~ ${schedule[${n3}]}:${schedule[${n4}]} "
  if [ ${H_1} -le 2 ] && [ ${H_2} -ge 0 ] && [ ${H_1} -ge 0 ] && [ ${H_2} -le 2 ]; then
    if [ ${H_3} -eq 2 ]; then
      if [ ${H_1} -eq 0 ]; then
          if [ ${M_1} -ge 0 ]; then
            #echo "flag 1"
            time=`expr ${time} - ${M_1}`
            echo "~${schedule[${n0}]}限終了まで残り ${time}分~"
          fi
      else
        if [ ${H_1} -eq 1 ]; then
          #echo "flag 2"
          time=`expr ${time} - $M - 60 + ${schedule[${n2}]}`
        else
          #echo "flag 3"
          time=`expr ${time} - $M - 120 + ${schedule[${n2}]}`
        fi
        echo "~${schedule[${n0}]}限終了まで残り ${time}分~"
      fi
    else
      if [ ${H_1} -eq 0 ]; then
        if [ ${M_1} -ge 0 ]; then
          #echo "flag 4"
          time=`expr ${time} - ${M_1}`
          echo "~${schedule[${n0}]}限終了まで残り ${time}分~"
        fi
      else
        if [ ${H_2} -eq 0 ]; then
          if [ ${M_2} -ge 0 ]; then
            #echo "flag 5"
            time=`expr ${time} - $M - 60 + ${schedule[${n2}]}`
            echo "~${schedule[${n0}]}限終了まで残り ${time}分~"
          fi
        fi
      fi
    fi
  fi
  i+=5
done
